version: '3.9'
services:
  postgres-db:
    image: 'postgres:14.5-alpine'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - '5433:5432'
    networks:
      - swapi-network
  swapi-planet-api:
    build: .
    restart: always
    working_dir: /swapi-planet-api
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB_NAME}
      SPRING.DATASOURCE.USERNAME: ${POSTGRES_DB_USER}
      SPRING.DATASOURCE.PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - '8080:8080'
    command: mvn spring-boot:run
    depends_on:
      - postgres-db
    networks:
      - swapi-network
networks:
  swapi-network:
    driver: bridge
volumes:
  postgres-data: