version: '3.9'
services:
  postgres-db:
    image: 'postgres:14.5-alpine'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - '5433:5432'
    networks:
      - swapi-network
  swapi-planet-api:
    build: .
    restart: always
    working_dir: /swapi-planet-api
    environment:
      TZ: America/Sao_Paulo
    ports:
      - '8080:8080'
    command: mvn spring-boot:run
    depends_on:
      - postgres-db
    networks:
      - swapi-network
networks:
  swapi-network:
    driver: bridge
volumes:
  postgres-data: