spring:
  application:
    name: swapi_planet_api
  datasource:
    url: jdbc:postgresql://localhost:5432/swapi-planet
    driverClassName: org.postgresql.Driver
    username: xxx
    password: xxx
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    properties:
      hibernate:
        format-sql: false