spring:
  config:
    import: ./application-secrets.yml
  application:
    name: swapi_planet_api
  datasource:
    url: jdbc:postgresql://localhost:5432/swapi_planet_db
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    properties:
      hibernate:
        format-sql: false